nodeLinker: node-modules

npmRegistries:
  //gitlab.com/api/v4/projects/45935297/packages/npm/:
    npmAlwaysAuth: true
    npmAuthToken: "${CI_JOB_TOKEN}"

npmScopes:
  tokene-q:
    npmPublishRegistry: "https://gitlab.com/api/v4/projects/45935297/packages/npm/"
    npmRegistryServer: "https://gitlab.com/api/v4/projects/45935297/packages/npm/"


yarnPath: .yarn/releases/yarn-3.6.0.cjs
